[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_runtime = "nodejs20.x"
  included_files = ["src/lib/db/schema.ts"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[npx.localtunnel]
  port = 1430
